apiVersion: v1
kind: Service
metadata:
  name: {{ include "eureka-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eureka-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8761
      protocol: TCP
  selector:
    {{- include "eureka-server.selectorLabels" . | nindent 4 }}

